# configuration for "master" branch
# build in Release mode and deploy to nuget.org
-
  branches:
    only:
      - master

    configuration: Release
    version: 0.3-{branch}-{build}

    init:
    - cmd: git config --global core.autocrlf true
    before_build:
    - cmd: nuget restore "Kajabity Tools.sln"

    build:
      verbosity: normal

    artifacts:
    - path: Kajabity Tools\bin\$(configuration)
      name: Kajabity.Tools.dll
    - path: Samples\CsvEditor\bin\$(configuration)
      name: CsvEditor.exe
    - path: Samples\HexViewer\bin\$(configuration)
      name: HexViewer.exe
    - path: Samples\JavaPropertiesEditor\bin\$(configuration)
      name: JavaPropertiesEditor.exe
    - path: Samples\TextEditor\bin\$(configuration)
      name: TextEditor.exe
    - path: '**\*.nupkg' # find all NuGet packages recursively

# configuration for all other branches.
# build in Debug mode
-
    configuration: Debug
    version: 0.3-{branch}-{build}

    init:
    - cmd: git config --global core.autocrlf true
    before_build:
    - cmd: nuget restore "Kajabity Tools.sln"

    build:
      verbosity: normal

    artifacts:
    - path: Kajabity Tools\bin\$(configuration)
      name: Kajabity.Tools.dll
    - path: Samples\CsvEditor\bin\$(configuration)
      name: CsvEditor.exe
    - path: Samples\HexViewer\bin\$(configuration)
      name: HexViewer.exe
    - path: Samples\JavaPropertiesEditor\bin\$(configuration)
      name: JavaPropertiesEditor.exe
    - path: Samples\TextEditor\bin\$(configuration)
      name: TextEditor.exe
    - path: '**\*.nupkg' # find all NuGet packages recursively

# Deploy to NuGet.org
deploy:
  provider: NuGet
  api_key:
    secure: r3ybnECBTOpYHj0EtDF6FMn5V38UX6qrTrf3uRya2v/XlqEp8Qm0z3cK/1+hAQSm
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

# Deploy to GitHub
deploy:
  release: kajabity.tools-v$(appveyor_build_version)
  description: 'Kajabity Tools Release v$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: qyEhOXLpH0txl0uO1Y3k99DUnjxsF2bmZydo8h7g05/fyNs+uj/ge+Qg273TsVU1
  draft: false
  prerelease: false
