#---------------------------------# 
#      general configuration      # 
#---------------------------------# 
 
# version format 
version: 0.3-{branch}-{build}

# branches to build
#branches

 
# Do not build on tags (GitHub only)
# This avoids the infinite build loop as Deploy to GitHub is set to create a tag each time.
skip_tags: true 

#---------------------------------# 
#    environment configuration    # 
#---------------------------------# 
 
# scripts that are called at very beginning, before repo cloning 
init:
    - cmd: git config --global core.autocrlf true

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to

#---------------------------------# 
#       build configuration       # 
#---------------------------------# 
 
# build platform, i.e. x86, x64, Any CPU. This setting is optional. 
platform: Any CPU 

# build Configuration, i.e. Debug, Release, etc.
before_build:
    - cmd: nuget restore "Kajabity Tools.sln"

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
    publish_nuget: true             # package projects with .nuspec files and push to artifacts 
    publish_nuget_symbols: true     # generate and publish NuGet symbol packages 
    include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts 
 
# MSBuild verbosity level 
    verbosity: normal

#---------------------------------# 
#      artifacts configuration    # 
#---------------------------------# 
 
artifacts:
    - path: Kajabity Tools\bin\$(configuration)\Kajabity.Tools.dll

    - path: Samples\CsvEditor\bin\$(configuration)\CsvEditor.exe

    - path: Samples\HexViewer\bin\$(configuration)\HexViewer.exe

    - path: Samples\JavaPropertiesEditor\bin\$(configuration)\JavaPropertiesEditor.exe

    - path: Samples\TextEditor\bin\$(configuration)\TextEditor.exe

      # Being more specific to avoid also identifying NUnit as an artefact.
    - path: Kajabity Tools\bin\$(configuration)\*.nupkg

#---------------------------------# 
#     deployment configuration    # 
#---------------------------------# 

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment 
# provider names are case-sensitive! 

deploy:

    # Deploying to NuGet feed
  - provider: NuGet
    api_key:
        secure: r3ybnECBTOpYHj0EtDF6FMn5V38UX6qrTrf3uRya2v/XlqEp8Qm0z3cK/1+hAQSm
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
        appveyor_repo_tag: true        # deploy on tag push only

        # not needed as only deploys on tag.  
        #branch: master                 # release from master branch only

    # Deploy to GitHub Releases 
  - provider: GitHub 
    release: kajabity.tools-v$(appveyor_build_version)
    description: 'Kajabity Tools Release v$(appveyor_build_version)'
    auth_token:
        secure: qyEhOXLpH0txl0uO1Y3k99DUnjxsF2bmZydo8h7g05/fyNs+uj/ge+Qg273TsVU1
    draft: false
    prerelease: false
